# -*- coding: utf-8 -*-
"""Reglas ordenadas de clasificación. Gana la primera que casa.
   Cada regla: (seccion, subgrupo, patrón regex sobre la definición en inglés)."""

REGLAS_EN = [
# ---------------- personas y cuerpo ----------------
("hito","familia", r"\b(father|mother|parent|son|daughter|brother|sister|uncle|aunt|cousin|nephew|niece|grandfather|grandmother|grandchild|husband|wife|bride|groom|family|sibling|married couple|in-law|ancestor|descendant|relative|kin)\b"),
("hito","cuerpo", r"\b(head|face|eye|eyeball|ear|nose|mouth|lip|tooth|teeth|tongue|throat|neck|shoulder|arm|elbow|wrist|hand|finger|thumb|nail|chest|breast|belly|stomach|abdomen|back \(of body\)|waist|hip|buttock|leg|foot|knee|heel|skin|bone|muscle|blood|nerve|brain|heart|lung|liver|hair|beard|moustache|eyelid|pupil \(of eye\)|cheek|forehead|body|navel|organ)\b"),
("hito","salud", r"\b(illness|sick|disease|ill\b|health|hygiene|medicine|medical|doctor|physician|nurse|hospital|clinic|patient|injur|wound|cure|heal|fever|cough|sneeze|headache|pain|ache|nausea|dizz|blood pressure|surgery|surgical|operation \(medical\)|injection|diagnos|drug|pharmac|symptom|infect|contagio|treatment|therap|virus|epidemic|bandage|burn, scald|cavity|tooth decay|numb|drown|faint|pregnan|birth control|hiccup|sanitation|disinfect|sterilization|nursing|vaccin)\b"),
("hito","apariencia", r"\b(beautiful person|good-looking|pretty|handsome|ugly|figure, shape, appearance|stature|height \(of body\)|slim|fat\b|thin\b|obes|complexion|dimple|wrinkle|freckle)\b"),
("hito","caracter", r"\b(character, personality|personality|temperament|disposition|selfish|greedy|generous|honest|dishonest|shy\b|timid|brave|coward|diligent|lazy|idle\b|stubborn|obstinate|gentle|cruel|kind(ness)?\b|modest|humble|arrogant|proud\b|clever|smart\b|wise|stupid|foolish|foolishness|naive|serious, earnest|patien(t|ce)|impudent|shameless|frank|sincere|virtue|nature \(of person\))\b"),
("hito","vida", r"\b(age\b|years old|birth\b|born\b|birthday|birth date|childhood|infant|baby|child|children|boy\b|girl\b|youth|young man|adult|grown-up|middle-aged|old age|old person|the aged|elderly|life span|lifetime|human life|die\b|death|dead\b|funeral|grave|tomb|corpse|suicide|survival|generation|juvenile|toddler|upbringing|childcare)\b"),
("hito","gente", r"\b(person|people|human being|man\b|woman\b|male\b|female\b|gentleman|lady\b|madam|mister|sir\b|guy\b|fellow|individual|citizen|inhabitant|resident|population|stranger|acquaintance|friend|neighbou?r|companion|partner|self\b|oneself|myself|mankind|humanity|race \(of people\)|nationality|surname|family name|full name|name, reputation|alias|pseudonym)\b"),

# ---------------- vida diaria ----------------
("kurashi","casa", r"\b(house|home\b|dwelling|residence|apartment|flat\b|room\b|living room|bedroom|kitchen|bathroom|toilet|lavatory|restroom|garden|yard\b|roof|wall|floor\b|ceiling|pillar|door|gate|window|entrance|entranceway|stairs|staircase|corridor|hallway|balcony|closet|alcove|storage room|storehouse|shed|hut|cabin|garage|fence|hedge|address \(e.g. of house\)|landlord|rent\b|lodging|boarding|tenant|moving \(dwelling|changing residence|building\b|eaves|tatami|sliding|screen door|storm door|well\b|basement|attic|drainage|sewage|plumbing|water supply|water service|faucet|tap\b)\b"),
("kurashi","muebles", r"\b(furniture|table\b|desk|chair|bench|sofa|couch|bed\b|shelf|shelves|rack|drawer|cupboard|wardrobe|locker|mirror|curtain|carpet|cushion|pillow|blanket|bedding|futon|mattress|lamp|candle|vase|clock|watch\b|umbrella|towel|soap|comb|razor|toothpaste|dentifrice|tissue paper|toilet paper|basket|bucket|pail|box\b|bag\b|sack|container|vessel|bottle|can, tin|jar\b|plate|dish\b|bowl|cup\b|glass\b|spoon|fork|chopstick|knife|kettle|pot\b|pan\b|tray|tableware|crockery|earthenware|pottery|napkin|ashtray|matchbox|match\b|broom|ladder|rope|string|cord|wire\b|nail\b|screw|thread|needle|scissors|key\b|lock\b|lid\b|cover, lid|stopper|cork|handle|grip|hook|tag|label)\b"),
("kurashi","comida", r"\b(food|foodstuff|meal|breakfast|lunch|dinner|supper|snack|rice\b|bread|noodle|soup|meat|fish\b(?!ing)|vegetable|fruit|egg|milk|cheese|butter|sugar|salt\b|pepper|soy sauce|miso|oil\b|flour|wheat|bean|pea\b|potato|carrot|onion|apple|orange|grape|peach|melon|candy|cake|sweets|pastry|confection|chocolate|ice cream|tea\b|coffee|juice|water \(drink|beer|wine|whisky|sake|alcohol|liquor|beverage|drink|gum|jam|salad|sandwich|sushi|sashimi|tofu|nutrition|nutrient|nourish|calorie|vitamin|grain|cereal|corn\b|crop|produce \(e.g. agricultural\)|provisions|rations|groceries)\b"),
("kurashi","cocina", r"\b(cook|cooking|cuisine|boil|fry|frying|grill|bake|roast|steam|stew|recipe|menu|seasoning|condiment|flavou?r|taste|delicious|tasty|sweet\b|sour|bitter|salty|spicy|appetite|hungry|thirst|chew|bite\b|swallow|serve \(food|helping, serving|dining|restaurant|cafeteria|feast|banquet|picnic|refreshment|lunch box|box lunch|pickle|ripen|rot\b|go bad|fresh\b)\b"),
("kurashi","ropa", r"\b(clothes|clothing|garment|wear\b|dress\b|shirt|blouse|skirt|trousers|pants|underpants|underwear|coat|jacket|suit\b|sweater|kimono|yukata|uniform|pyjama|nightclothes|sleep-wear|sock|stocking|shoe|footwear|sandal|boot\b|slipper|hat\b|cap\b|glove|scarf|muffler|belt\b|tie, necktie|necktie|button|pocket|sleeve|collar|apron|ring\b|necklace|brooch|jewel|accessory|cosmetic|make-up|lipstick|perfume|hairstyle|barber|beauty of figure|sewing|knit|sew\b|cloth|fabric|silk|wool|cotton|leather|fur\b|thread, yarn)\b"),
("kurashi","compras", r"\b(shop|store\b|shopping|buy|sell|sale\b|sold|purchase|customer|clerk|shop assistant|salesperson|shopkeeper|merchant|trader|market\b|supermarket|department store|stall|stand\b|goods|merchandise|commodity|article of commerce|product|stock\b|order, request|delivery|deliver|wrapping|packing|package|parcel|discount|bargain|free of charge|receipt|shop which handles)\b"),
("kurashi","dinero", r"\b(money|cash|coin|bill\b|banknote|paper money|price|cost|fee|charge|fare|payment|pay\b|salary|wage|income|revenue|expense|expenditure|budget|tax\b|taxation|bank\b|savings|deposit|loan|debt|profit|gain\b|loss\b|rich\b|wealth|poor|poverty|economis|saving|change, money exchange|exchange, interchange|currency|fortune, assets|property|finance|fund|investment|allowance|pocket money|refund|repay|balance, ebb|bankrupt|insurance|guarantee, security)\b"),
("kurashi","rutina", r"\b(get up|wake|wake up|sleep|asleep|nap\b|doze|dream|rest\b|break, recess|relax|bath\b|bathe|shower|wash\b|brush\b|shave|gargle|dressing|daily (lesson|work|routine|necessities)|everyday|habit|custom|manners|way of life|living, livelihood|lifestyle|housework|domestic chores|maid|caretaker|absence, being away|leisure|free time|spare time)\b"),
("kurashi","limpieza", r"\b(clean|cleaning|sweep|laundry|washing|detergent|dust\b|dirt\b|dirty|filthy|garbage|trash|rubbish|waste\b|scrap|litter|tidy|in order|neat|stain|pollut|contaminat|rust|mold|mildew|sanit|rag\b|dry cleaning)\b"),

# ---------------- tiempo y cantidad ----------------
("jikan","calendario", r"\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday|january|day of the week|week\b|weekly|weekday|month\b|monthly|year\b|yearly|annual|today|tomorrow|yesterday|day after tomorrow|day before yesterday|this year|last year|next year|new year|date\b|date and time|calendar|season|spring\b|summer|autumn|winter|holiday|vacation|festival|anniversar|era\b|epoch|century|fiscal year|dawn|daybreak|morning|noon|afternoon|evening|night|midnight|daytime|nightfall|sunset|sunrise|days\b|the .*(day|days) \(of the month\)|first of month)\b"),
("jikan","momento", r"\b(time\b|moment|instant|occasion|opportunity|chance\b|timing|now\b|present\b|nowadays|recently|lately|the other day|before long|soon|immediately|at once|already|still\b|yet\b|later|afterwards|beforehand|previous|former|future|past\b|beginning|start\b|end\b|finish|final|last\b|deadline|term, period|period|during|while\b|meanwhile|midway|interim|since|until|simultaneous|at the same time|suddenly|abruptly|all of a sudden|at last|finally|eventually|sometime|someday|early|late\b|delay|postpone|in advance|temporar|urgent|any time|for the time being)\b"),
("jikan","duracion", r"\b(long time|short term|duration|speed|velocity|rapid|fast\b|quick|slow|hurry|rush\b|prolong|continue|continuation|last\b, endure|permanent|eternal|eternity|momentar|brief)\b"),
("jikan","frecuencia", r"\b(always|usually|often|frequent|sometimes|occasionally|seldom|rarely|never|again|once more|repeat|repeatedly|every time|each time|number of times|counter for occurrences|constantly|continuously|one by one|in succession|gradually|steadily|little by little|now and then|regular|regularly)\b"),
("jikan","cantidad", r"\b(number|figure\b|amount|quantity|volume|capacity|total|sum\b|all\b|every|whole|entire|most\b|majority|half\b|part\b|portion|piece|some\b|few\b|little\b|many|much\b|plenty|abundan|enough|sufficient|insufficient|shortage|lack\b|excess|surplus|remainder|rest\b|left over|increase|decrease|reduce|add\b|subtract|multiplication|division \(math\)|average|percent|ratio|rate\b|proportion|fraction|decimal|integer|zero|maximum|minimum|extra|double|twice|per\b|majority|minority|countless|infinite)\b"),
("jikan","contadores", r"\b(counter for|numeral|ten thousand|hundred million|thousand|hundred\b|\bnine\b|\beight\b|\bseven\b|\bsix\b|\bfive\b|\bfour\b|\bthree\b|\btwo\b|\bone\b(?! )|\b10, ten\b|\b100,)"),
("jikan","orden", r"\b(order, turn|in order, in turn|order, sequence|turn \(in line\)|sequence|first\b|second\b|third\b|next\b|previous|last, final|beginning|precedence|priority|rank|grade|stage|step\b|series|serial|consecutive|following|subsequent|procedure|process\b)\b"),

# ---------------- lugar y movimiento ----------------
("basho","ubicacion", r"\b(place\b|location|position|spot|point on a map|site\b|area|region|zone|district|sector|vicinity|neighbou?rhood|environs|surroundings|direction|way, method|north|south|east|west|right hand side|left hand side|front\b|back\b|behind|above|below|under|top\b|bottom|middle|centre|center|side\b|edge|corner|inside|outside|interior|exterior|between|among|near|close by|far\b|distant|opposite|across|beyond|over there|here\b|there\b|where\b|everywhere|somewhere|here and there|up\b|down\b|horizontal|vertical|width|length|depth|height|distance|space, room|gap|crevice|border|boundary|limit)\b"),
("basho","ciudad", r"\b(city|town|street|road|avenue|highway|path|sidewalk|footpath|crossing|intersection|crossroad|bridge|park\b|plaza|square\b|station\b|airport|port\b|harbou?r|hotel|inn\b|restaurant|library|museum|theatre|theater|cinema|hall\b|auditorium|temple|shrine|church|castle|tower|factory|office\b|building|skyscraper|police box|post office|hospital|school building|public bath|toilet.*public|traffic light|signal|bus stop|parking|suburb|outskirts|downtown|rural|countryside|village|capital city)\b"),
("basho","transporte", r"\b(car\b|automobile|vehicle|bus\b|train\b|railway|railroad|subway|underground train|bicycle|motorcycle|truck|taxi|ship|boat|ferry|airplane|aeroplane|aircraft|jet\b|helicopter|rocket|wheel|tire|tyre|engine|brake|steering|drive\b|driving|ride\b|passenger|conductor|pilot|ticket|fare|commut|traffic|transportation|transport|freight|cargo|luggage|baggage|platform|express|limited express|departure of a vehicle|schedule|timetable|derail|collision|accident)\b"),
("basho","viaje", r"\b(travel|trip\b|journey|tour|sightseeing|tourist|excursion|hike|hiking|camp\b|camping|guide\b|guidance|map\b|route|itinerary|souvenir|passport|visa\b|abroad|overseas|stay\b, sojourn|lodging|guest|visitor|welcome|reception|farewell|see off|arrival|arrive|depart|return home|hot spring|spa\b|resort|leisure)\b"),
("basho","mundo", r"\b(country|nation|national|international|foreign|world|earth\b|globe|continent|prefecture|province|state\b, country|government office|border|america|europe|asia|africa|japan|japanese|english language|china|west\b, western|orient|overseas|island|peninsula)\b"),
("basho","ir_venir", r"\b(to go\b|to come\b|to arrive|to leave|to depart|to enter|to exit|to return|to pass\b|to pass by|to cross|to walk|to run\b|to fly|to jump|to climb|to ascend|to descend|to get off|to alight|to board|to approach|to draw near|to follow|to chase|to escape|to flee|to wander|going|coming|entrance and exit|in and out|coming and going|round trip|way out|exit\b|entrance\b|detour)\b"),

# ---------------- naturaleza ----------------
("shizen","clima", r"\b(weather|climate|rain\b|rainy|snow|wind\b|windy|storm|typhoon|thunder|lightning|cloud|cloudy|fog\b|mist|frost|ice\b|hail|humid|humidity|moisture|dry, arid|sunny|clear weather|fine weather|temperature|cold \(e.g. weather\)|hot, warm|warmth|atmospheric pressure|forecast|shower \(rain\)|rainy season|breeze|air conditioning|heating)\b"),
("shizen","cielo", r"\b(sky|universe|cosmos|space\b|star\b|planet|sun\b|solar|moon\b|satellite|light ray|sunlight|sunshine|shadow|shade|dark\b|darkness|bright|air, atmosphere|atmosphere\b|gravity|horizon|rainbow|eclipse)\b"),
("shizen","tierra", r"\b(mountain|hill|valley|cliff|slope|field\b|plain\b|prairie|forest|woods|desert|cave|rock\b|stone|soil|earth, soil|ground|land\b|territory|geography|geological|volcano|lava|cape \(on coast\)|basin|arable|terrain|surface of the earth|equator|pole\b|latitude|longitude)\b"),
("shizen","agua", r"\b(water|sea\b|ocean|lake|river|stream|pond|marsh|spring, fountain|fountain|waterfall|wave\b|tide|beach|coast|shore|bank, coast|flood|swim|swimming|dive|drown|fresh water|sea bathing|canal|moat|drop of water|steam|vapou?r|bubble|foam)\b"),
("shizen","plantas", r"\b(plant\b|plants|vegetation|tree|forest tree|flower|blossom|cherry blossom|grass|lawn|leaf|leaves|branch|root|seed|bud|sprout|stem|bamboo|pine|maple|cedar|plum|rice-plant|weed|bloom|wither|garden shrub|horticulture|gardening|agricultural produce)\b"),
("shizen","animales", r"\b(animal|bird|fowl|poultry|dog|cat\b|horse|cow|cattle|pig\b|sheep|goat|monkey|mouse|rat\b|rabbit|tiger|lion|bear\b|elephant|snake|frog|insect|bug\b|butterfly|mosquito|fly\b|bee\b|spider|shell|shellfish|fish\b|whale|wing|feather|tail|claw|horn\b|nest|egg\b, spawn|zoo|livestock|stock-farming|pet\b)\b"),
("shizen","materia", r"\b(material|substance|matter\b, substance|element|chemical|chemistry|metal|iron|steel|gold|silver|copper|lead\b|tin\b|mineral|coal|petroleum|oil, petroleum|gas\b|liquid|solid|powder|glass, pane|plastic|rubber|paper|wood|lumber|timber|brick|cement|concrete|clay|sand|ash\b|smoke|flame|fire\b|burn|oxygen|hydrogen|carbon|acid|molecule|atom|raw material|ingredient|component|composition)\b"),
("shizen","desastre", r"\b(disaster|calamity|earthquake|eruption|fire, conflagration|conflagration|flood|drought|famine|accident|danger|dangerous|peril|hazard|risk|emergency|rescue|relief, aid|safety|safe\b|escape|damage|destruction|extinction|crisis|critical|warning|alarm|explosion|explode)\b"),

# ---------------- escuela ----------------
("gakkou","escuela", r"\b(school|university|college|kindergarten|classroom|campus|pupil|student|teacher|professor|lecturer|principal|graduate|graduation|enroll|admission|entry to school|matriculation|class\b|grade in school|term \(school\)|semester|homework|lesson|class work|timetable|dormitory|hostel|club|seminar|scholarship|tuition|schoolmate|junior \(at work or school\)|senior \(at work or school\))\b"),
("gakkou","estudio", r"\b(study|learn|learning|teach|instruct|education|educational|training|practice|practise|exercise\b|drill|review, revision|preparation for a lesson|memoriz|memorization|self-study|research|knowledge|scholarship|erudition|skill|ability|talent|effort|endeavou?r|explanation|explain|understand|comprehension)\b"),
("gakkou","examen", r"\b(exam|examination|test\b|quiz\b|question, inquiry|answer, solution|marking|grading|score|marks, points|results, record|pass\b|fail|success, passing|correct|mistake|error|blunder|absence, non-attendance|attendance|application, request)\b"),
("gakkou","lengua", r"\b(language|word\b|words|vocabulary|letter \(of alphabet\)|character|kanji|hiragana|katakana|kana|syllabary|alphabet|pronunciation|accent|grammar|sentence|phrase|clause|verb\b|noun|adjective|adverb|pronoun|particle|conjugation|subject \(gram|predicate|dialect|translation|translate|interpret|idiom|proverb|expression, wording|speech, expression|term, terminology|radical \(of a kanji|stroke|punctuation|comma|orthography|meaning, significance|abbreviation|dictionary|synonym)\b"),
("gakkou","libros", r"\b(book|books|publication|publish|magazine|journal|newspaper|novel|story|tale|essay|poem|poetry|thesis|paper\b|article|manuscript|text\b|textbook|notebook|diary|document|paper, notes|read\b|reading|write\b|writing|author|writer|editor|editing|print|printing|page\b|title|index|chapter|library|literature|comic|cartoon|encyclopedia|reference|catalog|note, notes|memo|letter to the editor|correspondence)\b"),
("gakkou","materias", r"\b(mathematics|arithmetic|algebra|geometry|physics|science|biology|chemistry|history|geography|philosophy|psychology|economics|medicine, medical science|law\b, legal|engineering|technology, technique|academic|discipline|subject of study|curriculum|course of study|scientific|theory|principle|formula|equation|experiment|observation|analysis|research)\b"),

# ---------------- trabajo y sociedad ----------------
("shigoto","trabajo", r"\b(work|job\b|labor|labour|employ|employment|employee|employer|occupation|duty|duties|task|business\b|office work|overtime|shift\b|career|colleague|coworker|boss|chief|manager|director|staff|personnel|retire|retirement|resign|dismiss|hire|recruit|salary|commuting to work|going to work|workplace|post\b|position \(job|responsibility|charge\b|in charge|meeting|conference|report|application|interview|contract|training)\b"),
("shigoto","empresa", r"\b(company|corporation|firm\b|enterprise|organization|association|union|branch (store|office)|headquarters|department|division|section|committee|member|management|administration|president|executive|board\b|trading company|factory|plant, mill|workshop|shop, business firm)\b"),
("shigoto","oficios", r"\b(farmer|fisherman|carpenter|cook\b|chef|waiter|waitress|driver|clerk|engineer|technician|scientist|scholar|artist|painter|musician|singer|actor|actress|writer, novelist|journalist|reporter|announcer|lawyer|judge|police|policeman|soldier|nurse|doctor \(medical\)|dentist|barber|tailor|craftsman|artisan|mechanic|worker|servant|maid|guard|official|civil servant|specialist|expert|master, expert|professional|apprentice|assistant)\b"),
("shigoto","economia", r"\b(econom|industry|industrial|commerce|commercial|trade\b|business condition|market\b|production|produce, manufacture|manufacture|manufacturing|consumption|consumer|supply|demand|distribution|import|export|inflation|competition|capital|investment|stock, share|share, stock|advertisement|advertising|publicity|propaganda|marketing|sales|efficiency|productivity|resources|development, growth|growth)\b"),
("shigoto","politica", r"\b(politic|government|governmental|administration|state, country|nation-wide|parliament|congress|diet\b|assembly|minister|cabinet|prime minister|president, chief executive|governor|mayor|election|vote|voting|poll|candidate|party \(political\)|policy|reform|revolution|democracy|independence|diplomacy|ambassador|consul|treaty|official business|public office|public service|bureau|ministry|prefectural office|authority|authorities)\b"),
("shigoto","ley", r"\b(law\b|laws|legal|constitution|rule\b|rules|regulation|act \(law|justice|court|trial|judgement|judge|jury|lawyer|crime|criminal|offender|thief|robber|burglar|theft|robbery|steal|murder|kill\b|arrest|capture|prison|punish|penalt|fine\b|guilty|innocent|witness|evidence|investigation \(police|detective|violation|infringement|breach|permission|permit|license|prohibit|ban\b|forbid|right, privilege|obligation|duty, obligation|responsibility|contract, compact|signature|seal \(used for signature\)|document, official)\b"),
("shigoto","guerra", r"\b(war\b|battle|fight, battle|army|military|troops|soldier|navy|weapon|arms\b|gun\b|rifle|pistol|bomb|bullet|shell|sword|attack|defen[sc]e|invasion|enemy|ally|victory|defeat|peace|surrender|self-defense|conquest|strategy|troops|force, troops)\b"),
("shigoto","sociedad", r"\b(society|social|public\b|community|welfare|discrimination|equality|freedom|liberty|human rights|custom, habit|tradition|culture|civilization|generation|class\b, group|group, mass|institution|system, institution|organization, composition|census|statistics|survey|population|urbanization|environment)\b"),
("shigoto","campo", r"\b(agricultur|farm|farming|farmer|farm family|field, plough|rice field|paddy|harvest|crop|sow\b|plant, grow|cultivat|plow|plough|till\b|irrigat|fertilizer|agricultural chemical|livestock|pasture|ranch|fishing|fishery|fisherman|hunt|forestry|mine\b|mining|coal mine)\b"),

# ---------------- sentimientos ----------------
("kokoro","alegria", r"\b(happy|happiness|joy|glad|delight|pleasure|pleasant|enjoy|fun\b|amusing|amusement|smile|laugh|cheerful|bright, cheerful|comfort|relief|relieved|satisfaction|satisfied|gratitude|thankful|grateful|hope|blessing|lucky|good luck|fortunate|excitement|excited|interest \(in something\)|interesting|love|affection|like\b, fond|fondness|admiration|admire|respect|praise|congratulat|celebrat)\b"),
("kokoro","tristeza", r"\b(sad|sorrow|grief|mourn|cry\b|weep|tear\b|lonely|lonesome|painful|suffer|distress|worry|worried|anxiety|anxious|uneasy|fear|afraid|scared|frightening|terrible|dread|horror|terror|panic|angry|anger|mad\b|rage|hate|hatred|detest|dislike|disgust|jealous|envy|envious|regret|regrettable|shame|ashamed|embarrass|disappoint|despair|discontent|dissatisf|complain|complaint|boring|bored|tedium|tired|fatigue|weary|nervous|tension|stress|pity|pitiful|miserable|unhappy|misfortune|unlucky|trouble|bother|annoy|hardship|difficult, distress|resent|bitter, feel|vexing|mortifying)\b"),
("kokoro","deseo", r"\b(desire|wish|want\b|wanted|hope, wish|aspiration|ambition|will, volition|intention|purpose|motive|eager|zeal|enthusiasm|passion|greed|avarice|longing|yearn|dream\b|ideal|expectation|anticipat|demand, request)\b"),
("kokoro","relaciones", r"\b(friendship|fellowship|association, socializing|company, friendship|acquaintance|relationship|relation, connection|dating|date\b|marriage|marry|wedding|engagement|betrothal|divorce|love, tender|lover|sweetheart|girl ?friend|boy ?friend|couple|cooperation|collaboration|help\b|assist|assistance|support|aid\b|favou?r|kindness|trust|confidence|reliance|betray|quarrel|argument|dispute|reconcil|apolog|forgive|invite|invitation|visit|guest\b|host\b|introduc|meet\b|meeting, rendezvous|encounter|part from|separat|farewell|greeting|salutation)\b"),
("kokoro","saludos", r"\b(good morning|good day|good evening|good night|hello|goodbye|good-bye|thank you|excuse me|sorry\b|i beg your pardon|congratulations|welcome|please\b|you are welcome|don't mention it|how do you do|pleased to meet you|expression of gratitude|see you|take care|may i come in|i'?m home|here i am|it doesn'?t matter|certainly!|damn it|all right, fine|bow\b|greet)\b"),
("kokoro","actitud", r"\b(attitude|manner\b|manners|behavio|conduct|etiquette|politeness|polite|courteous|courtesy|rude|impolite|discourtesy|respect|honou?r|humility|modesty|arrogan|serious|earnest|careful|caution|carelessly|thoughtless|patience|endurance|persever|effort|diligen|lazy|neglect|obedient|docile|disobedience|selfish|wilful|violent|rough, rude|gentle|calm|composure|coolness|nervous|confus|hesitat|reluctant|willing|active|passive|positive|negative|optimis|pessimis|indifferen|sincere|frank|joke|jest|tease|prank|mimicry|imitation|pretense|show off|boast|pride)\b"),

# ---------------- acciones ----------------
("dousa","dar_recibir", r"\b(to give|to receive|to hand over|to pass over|to offer|to present|to award|to confer|to accept|to obtain|to get\b|to gain|to take, to pick up|to lend|to borrow|to rent|to return something|to send|to deliver|to forward|to bring|to take on board|to supply|to provide|to distribute|to share|to exchange|to entrust|to deposit|to donate|contribution|donation|gift|present, gift)\b"),
("dousa","mano", r"\b(to hold|to carry|to grasp|to seize|to grip|to catch|to pick up|to pull|to push|to press|to touch|to rub|to throw|to cast|to hit\b|to strike|to beat|to knock|to tie|to bind|to fasten|to unfasten|to wrap|to fold|to tear|to cut\b|to slice|to chop|to dig|to stir|to shake|to wave|to open|to close|to shut|to turn \(a|to lift|to raise|to lower|to hang|to insert|to pull out|to squeeze|to wring|to peel|to scratch|to polish|to wipe|to sweep|to pour|to fill|to empty|to sprinkle|to scatter|to pile|to stack|to press down)\b"),
("dousa","movimiento", r"\b(to stand|to sit|to lie down|to bend|to lean|to turn around|to face|to bow|to kneel|to crawl|to creep|to jump|to leap|to dance|to swim|to kick|to step on|to tread|to stumble|to fall|to slip|to roll|to tumble|to shiver|to tremble|to stretch|to yawn|to breathe|to blink|to nod|to squat|posture)\b"),
("dousa","hacer", r"\b(to make|to create|to build|to construct|to produce|to manufacture|to assemble|to repair|to fix|to mend|to correct|to prepare|to arrange|to organize|to plant|to grow|to raise|to bring up|to develop|to improve|to increase|to expand|construction|manufacture|production, manufacture|invention|invent|design|plan, design|repair)\b"),
("dousa","romper", r"\b(to break|to smash|to destroy|to crush|to tear|to burn\b|to melt|to spill|to drop|to lose|to waste|to abandon|to throw away|to remove|to erase|to delete|to cancel|to reduce|to decrease|to disappear|to vanish|to die out|to spoil|to damage|to injure|to hurt|to kill|to steal|to cheat|to deceive|to betray|damage|destruction|failure|break-down)\b"),
("dousa","colocar", r"\b(to put\b|to place|to set\b|to lay|to leave \(behind|to keep|to store|to save|to collect|to gather|to pack|to insert|to include|to contain|to enter into|to take out|to pull out|to bring in|to line up|to arrange in|to hide|to conceal|to cover|to bury|to attach|to join|to connect|to add\b|to append|to fit|to install)\b"),
("dousa","percepcion", r"\b(to see|to look|to watch|to gaze|to stare|to glance|to observe|to hear|to listen|to sound|to smell|to taste|to feel|to touch, to feel|to notice|to recognize|to perceive|to appear|to seem|to be seen|to be visible|to be heard|to show|to display|to indicate|sight|view\b|scene|scenery|appearance|sound|noise|voice|smell|odou?r|fragrance|sense|sensation|feeling, sensation|impression|conscious)\b"),
("dousa","conflicto", r"\b(to fight|to compete|to struggle|to attack|to defend|to protect|to oppose|to resist|to argue|to quarrel|to win|to lose \(a game\)|to defeat|to beat\b|match\b|game\b|contest|competition|victory|defeat|opponent|rival|referee|umpire)\b"),

# ---------------- pensar y comunicar ----------------
("kotoba","pensar", r"\b(to think|to consider|to suppose|to imagine|to guess|to assume|to expect|to remember|to recall|to forget|to doubt|to wonder|to reflect|thought|thinking|idea|notion|concept|imagination|memory|recollection|reason\b|logic|consciousness|mind\b|mentality|intellect|intelligence|wisdom|common sense|attention|concentration|thought, idea)\b"),
("kotoba","saber", r"\b(to know|to understand|to realize|to learn of|to be aware|to be informed|to discover|to find out|to notice, to recognize|knowledge, information|information|understanding, comprehension|misunderstanding|comprehension|conscious|acquainted)\b"),
("kotoba","decir", r"\b(to say|to speak|to tell|to talk|to state|to mention|to express|to declare|to announce|to report|to explain|to describe|to whisper|to shout|to cry out|to call\b|to call out|to name|to chat|to chatter|to converse|conversation|speech|talk\b|announcement|statement|report, information|expression, presentation|remark)\b"),
("kotoba","preguntar", r"\b(to ask|to inquire|to question|to answer|to reply|to respond|question|inquiry|query|answer|reply|response|request|demand|appeal|invitation|consultation|advice|suggestion|proposal|propose|recommend)\b"),
("kotoba","opinion", r"\b(opinion|view\b|viewpoint|point of view|standpoint|argument|discussion|debate|dispute|controvers|criticism|critic|comment|assert|insist|claim|agree|agreement|approval|consent|object|opposition, resistance|conclusion|persuade|convince|emphasis|stress)\b"),
("kotoba","verdad", r"\b(truth|true\b|real\b|reality|fact\b|genuine|actual|correct|right, just|wrong\b|false|lie\b, falsehood|falsehood|deceive|pretend|secret|mystery|rumou?r|gossip|proof|prove|verification|certain|sure\b|doubt|suspicious|possib|impossib|probab)\b"),
("kotoba","decidir", r"\b(to decide|to determine|to choose|to select|to appoint|to permit|to allow|to approve|to refuse|to decline|to give up|to abandon, to resign|decision|determination|choice|selection|plan\b|planning|project|schedule|program|preparation|arrangement|resolution|purpose, goal|goal|aim\b|target|objective|policy|method|means|measure|way, method|procedure|strategy|order, command|command|instruction|control|manage)\b"),

# ---------------- cualidades ----------------
("seishitsu","forma", r"\b(big|large|small|tiny|huge|gigantic|enormous|vast|wide|narrow|broad|thick|thin\b|long\b|short\b|tall|high\b|low\b|deep|shallow|round|circle|square|triangle|rectangle|straight|curve|angle|shape|form\b|figure, shape|pattern|model|type, style|flat|smooth|rough|sharp|pointed|dull|heavy|light \(not heavy\)|weight|size|dimension|measurement|scale)\b"),
("seishitsu","color", r"\b(colou?r|red\b|blue|green|yellow|white|black|brown|grey|gray|purple|violet|pink|orange \(colour\)|navy|light brown|pale|dark, gloomy)\b"),
("seishitsu","valoracion", r"\b(good\b|nice|fine\b|excellent|splendid|wonderful|magnificent|superb|great\b|best\b|better|superior|first class|high class|high grade|quality|bad\b|worse|worst|inferior|poor\b, needy|terrible|awful|horrible|useless|no good|worthless|important|essential|necessary|valuable|precious|useful|convenient|inconvenient|suitable|appropriate|proper|adequate|reasonable|strange|odd\b|unusual|rare|common|ordinary|usual|normal|special|particular|unique|beautiful|lovely|clean\b|pretty|ugly|new\b|old\b|fresh|safe|dangerous|comfortable|pleasant|unpleasant)\b"),
("seishitsu","dificultad", r"\b(difficult|difficulty|hard\b, difficult|easy|simple|simplicity|complex|complicat|elaborate|troublesome|tiresome|bother to do|skillful|skilled|clumsy|awkward|unskillful|expert|beginner|amateur|novice|possible|impossible|able\b|ability|capable|efficien)\b"),
("seishitsu","grado", r"\b(very|extremely|exceedingly|quite|considerably|fairly|rather|somewhat|slightly|a little|a bit|hardly|barely|scarcely|almost|nearly|completely|entirely|thoroughly|absolutely|perfectly|totally|utterly|really|truly|surely|certainly|indeed|too much|excessive|more\b|most\b|less\b|least\b|degree|extent|level, standard|standard|grade, rank|intensity|strong|weak|powerful|force, vigor|energy|violent|intense|severe|strict|mild|moderate)\b"),
("seishitsu","comparacion", r"\b(compare|comparison|comparative|contrast|difference|differ\b|different|discrepanc|same\b|identical|equal|similar|resemble|like, such as|as expected|distinction|distinguish|classification|classify|category|kind, type|variety|sort\b|opposite|reverse|contrary|instead|substitut|replace|exchange)\b"),
("seishitsu","estado", r"\b(condition|state\b|situation|circumstance|status|appearance, air|aspect|form, formality|order\b, system|disorder|chaos|confusion|balance|stability|stable|change|changing|variation|alteration|transform|develop|progress|advance|decline|deteriorat|complete|completion|perfect|incomplete|ready|finish|continu|stop\b|suspension|interruption|existence|exist|presence|absence|available|empty|full\b|open\b|closed|free\b|busy|quiet|noisy|calm\b|peaceful|dirty|wet\b|dry\b|hot\b|cold\b|warm\b|cool\b|soft|hard\b|tight|loose|firm)\b"),

# ---------------- técnica, cultura ----------------
("gijutsu","maquinas", r"\b(machine|mechanism|machinery|device|apparatus|equipment|instrument|engine\b|motor\b|robot|computer|automatic|automation|switch|button, knob|lever|gear|cog-wheel|pump|elevator|escalator|refrigerator|washing machine|sewing machine|air conditioner|cooler|fan\b|heater|stove|camera|telephone|television|radio\b|recorder|projector|printer|copy machine|typewriter|calculator|abacus|microscope|telescope|meter \(clock\)|battery|installation|facility|facilities)\b"),
("gijutsu","energia", r"\b(electric|electricity|electron|current|voltage|power\b|energy|nuclear|atomic|generation \(e.g. power\)|fuel|kerosene|lamp oil|light bulb|lamp\b|lighting|electric light|magnet|wave\b, electro|radio wave|circuit|resistance, electrical|charge, electric)\b"),
("gijutsu","medios", r"\b(communication|telephone|telegram|mail\b|postal|post\b, mail|letter\b|envelope|stamp|postcard|broadcast|television|radio|news\b|newspaper|press\b|media|program \(e.g. tv\)|advertisement|announcement|notice|notification|signal|message|contact|connection, contact|interview|journalis|internet|network)\b"),
("gijutsu","herramientas", r"\b(tool|implement|utensil|instrument\b|hammer|saw\b|nail|screwdriver|scissors|knife|blade|needle|thread|rope, cord|chain|ladder|brush|pencil|pen\b|eraser|ruler|ink\b|glue|paste|stationery|writing brush|weighing machine|scales|thermometer)\b"),
("gijutsu","arte", r"\b(art\b|arts|artist|painting|picture|drawing|sketch|photograph|photo\b|sculpture|carving|engraving|design\b|calligraphy|craft|handicraft|industrial arts|exhibition|gallery|museum|masterpiece|work, opus|performance|theatre|theater|play \(theatrical\)|drama|film|movie|cinema|stage\b|actor|director|beauty, aesthetic|decorat|ornament|pattern, figure, design)\b"),
("gijutsu","musica", r"\b(music|musical|song|sing\b|singer|melody|rhythm|tune|tone\b|chorus|orchestra|band\b|concert|instrument, musical|musical instrument|piano|guitar|violin|drum|flute|bell|record\b, audio|recording|noise \(jarring|composer|composition, setting)\b"),
("gijutsu","deporte", r"\b(sport|athlet|exercise, physical|gymnastics|training|team|player|match, game|competition|tournament|championship|race\b|running|swimming|baseball|soccer|football|tennis|golf|ski|skate|surf|marathon|judo|sumo|karate|boxing|coach|referee|stadium|ground \(sports\)|goal|score, runs)\b"),
("gijutsu","ocio", r"\b(play\b|game\b|toy|hobby|pastime|amusement|entertainment|recreation|leisure|festival|fair\b|party\b|dance\b|card|cards|chess|puzzle|riddle|joke|comic|fireworks|zoo|amusement park|picnic|holiday, day off|vacation|collection|fishing, angling|gambling|lottery)\b"),
("gijutsu","creencias", r"\b(religion|religious|god\b|buddha|buddhist|shinto|shrine|temple|church|priest|monk|pray|prayer|worship|faith|belief|soul|spirit|ghost|devil|demon|angel|heaven|hell|myth|legend|fairy tale|superstition|fortune-telling|ceremony|ritual|rite\b|wedding ceremony|funeral|new year|festival, feast|celebration|custom, tradition|luck, fortune|fate|destiny)\b"),

# ---------------- conectores y afijos ----------------
("tsunagu","conjunciones", r"\b(but\b|however|although|though|nevertheless|therefore|so\b, therefore|because|since\b|and\b|also|besides|moreover|furthermore|in addition|on the other hand|meanwhile|then\b|thereupon|otherwise|or\b|either|if\b|even if|in that case|by the way|as a result|consequently|accordingly|that is to say|in other words|in short|after all|anyway|anyhow|at any rate|nevertheless)\b"),
("tsunagu","kosoado", r"\b(this\b|that\b|these|those|here\b|there\b|over there|such, like this|such, like that|this way|that way|this side|the other side|in this way|to that extent|so, like this)\b"),
("tsunagu","pronombres", r"\b(who\b|what\b|when\b|where\b|why\b|how\b|which\b|whose|someone|somebody|something|somewhere|anything|anyone|nothing|nobody|everyone|everything|i, myself|you \(|he\b|she\b|they\b|we\b|us\b|him\b|her\b|it, that|oneself, personally)\b"),
("tsunagu","formulas", r"\b(expression of|phrase|it can'?t be helped|it should be so|no wonder|of course|by all means|as much as possible|at least|at most|as a matter of fact|to tell the truth|in fact|for example|such as|and so on|et cetera|and the like|more or less|for the time being|somehow|one way or another)\b"),
("tsunagu","adverbios", r"\b(suddenly|gradually|slowly|quickly|carefully|clearly|plainly|exactly|precisely|directly|mainly|especially|particularly|generally|mostly|probably|perhaps|maybe|certainly|surely|definitely|never|always|only|just\b|merely|simply|even\b|still\b|already|yet\b|soon|firmly|tightly|quietly|silently|deeply|widely|freely|properly|naturally|unfortunately|fortunately|luckily|actually|apparently|seemingly|somehow)\b"),
]

# Reglas por kanji presente (respaldo cuando la definición no dijo nada útil)
REGLAS_KANJI = [
 ("hito","cuerpo", "体肉骨血肌髪目耳鼻口歯舌喉首肩腕手指足膝腰胸腹背脳筋皮爪"),
 ("hito","familia", "父母兄弟姉妹祖孫嫁婿夫妻娘族親戚"),
 ("hito","salud", "病医薬疫痛療診患看護傷薬"),
 ("kurashi","casa", "家屋室戸door窓壁床台所庭門塀畳襖障柱屋根宿"),
 ("kurashi","comida", "食飲飯米麦豆肉魚菜果茶酒菓糖塩油味噌汁"),
 ("kurashi","ropa", "服着衣帽靴袖布糸綿絹革帯"),
 ("kurashi","dinero", "金銭円価費税料払買売貯銀"),
 ("jikan","calendario", "年月日曜週時季春夏秋冬朝昼夜晩"),
 ("basho","transporte", "車電船機航駅道路橋交通乗降"),
 ("basho","ciudad", "町市街村区都府県館店屋場所"),
 ("shizen","clima", "天気雨雪風雲晴曇雷霧嵐温湿"),
 ("shizen","tierra", "山川海地土石岩森林野原谷丘島"),
 ("shizen","animales", "動物犬猫馬牛鳥虫魚獣鶏豚羊"),
 ("shizen","plantas", "植木花草葉枝根実種竹松桜稲"),
 ("gakkou","escuela", "学校生徒教師授業講義科"),
 ("gakkou","lengua", "語文字言話読書訳詞"),
 ("shigoto","trabajo", "働仕事職務勤業員社役"),
 ("shigoto","politica", "政府国民議院党選挙官"),
 ("shigoto","ley", "法律罪犯警察裁判刑"),
 ("shigoto","guerra", "戦争軍兵武銃爆"),
 ("kokoro","tristeza", "悲苦痛怒憎恐怖泣悩憂"),
 ("kokoro","alegria", "喜楽happy幸笑嬉愛好"),
 ("gijutsu","energia", "電気力熱燃灯光"),
 ("gijutsu","maquinas", "機械器具装置"),
 ("gijutsu","musica", "音楽歌曲奏唱"),
 ("gijutsu","arte", "芸術絵画写真彫劇演"),
 ("gijutsu","deporte", "運動技競走泳球"),
 ("jikan","cantidad", "数量計測個数倍割"),
 ("seishitsu","color", "色赤青白黒黄緑紫"),
]

# Segunda tanda: sólo se aplica a lo que no casó con nada arriba.
REGLAS_EN2 = [
("seishitsu","estado", r"\b(improvement|betterment|amendment|correction|revision|modification|reform|strengthen|intensify|reinforce|solidify|expansion|enlargement|magnification|extension|elongation|prolongation|postponement|adjournment|supplement|appendix|acceleration|circulation|rotation, cycle|cycle|liberation|emancipation|release|restraint|reserve|fixed, settled|definite|elements, rudiments|foundation, basis|basis|standard|level\b|elementary level|exception|identity, sameness)\b"),
("seishitsu","valoracion", r"\b(complexity|complication|accuracy|accurate|precise|exactness|fitness|suitability|adequacy|relevance|superiority|excellence|uniqueness|peculiarity|delicate|subtle|transparen|irregular|unsteadi|disorderly|injustice|unfairness|inconvenience|inexpedien|disadvantage|handicap|unfavorable|drawback|futility|uselessness|absurd|nonsense|fame\b|famous|obvious|evident|greatness|varied, various|various|sly, cunning|prosperous|popularity|noble|pure\b|clear, pure|modern|classic|rational|naked|nude|oblique|dim, gloomy|smoky|itchy|unexpected|discomfort|disability|destitution)\b"),
("kokoro","actitud", r"\b(diffidence|discretion|prudence|frankness|candour|openheartedness|filial piety|daze|trance|ecstasy|delirium|engrossment|disregard, ignore|dozing|nodding off|threaten|coerce|scold|condemn|blame|criticize|dealing with|receiving, dealing)\b"),
("dousa","hacer", r"\bto (deepen|heighten|broaden|propagate|amass|accumulate|abbreviate|paint|plaster|lacquer|varnish|detain|check, to restrain|restrain|omit|eliminate|curtail|economize|deny|negate|contradict|need|be continued|be based on|be grounded|originate)\b"),
("dousa","mano", r"\b(to be caught|to be found|to be discovered|to be stuck|to be overturned|to be upset|to topple|to collapse|to crumble|friction|rubbing|rubdown|chafe|firing, shooting|discharge)\b"),
("kotoba","saber", r"\b(to be understood|experience|to be surprised|to be astonished|to become confused|calculation, counting)\b"),
("hito","cuerpo", r"\b(eyelid|spectacles|glasses|breath|respiration|starve|thirsty)\b"),
("kurashi","muebles", r"\b(chopstick|flag|chimney|tape\b|poster|slide\b|microphone|mike\b|feed, bait|vinegar|tobacco|cigarette|sign, mark|chart, diagram|graph\b)\b"),
("kurashi","ropa", r"\b(jeans|jean\b|stocking|eyeglasses)\b"),
("gijutsu","energia", r"\b(air-conditioning|cooling|pollution|contamination)\b"),
("jikan","cantidad", r"\b(subtraction|digit|milli-|centi-|acidity|neuter gender)\b"),
("tsunagu","formulas", r"\b(thus\b|so\b|according to|hurrah|cheers|randomly|recklessly|blindly|in your care)\b"),
]


# Tercera tanda: sustantivos abstractos de N1, que la lista trae sin categoría
# gramatical y con definiciones de una sola palabra.
REGLAS_EN3 = [
("dousa","abstractas", r"\b(combination|amalgamation|merger|fusion|substitution|replacement|appointment|nomination|ordination|pursuit|chase\b|achievement|accomplishment|enactment|establishment|foundation, establishment|abolition|repeal|abolish|separation|detachment|segregation|division, separation|coexistence|isolation|compromise|assassination|exile|banishment|retreat|withdrawal|confrontation|showdown|neutraliz|counteract|yield, produce|production, yield|adjustment|expansion|reduction|restoration|revival|renewal|repetition|imitation|adoption|application|installation|removal|abandonment|preservation|maintenance|promotion|demotion|transfer|conversion|transformation|circulation|distribution|allocation|accumulation|elimination|exclusion|inclusion|integration|unification|dissolution|suspension|resumption|interruption|intervention|mediation|negotiation|reconciliation|cooperation|competition|comparison, contrast|selection, choice|inspection|supervision|regulation|restriction|liberation|persecution|oppression|exploitation|sacrifice|dedication|devotion|commitment)\b"),
("seishitsu","conceptos", r"\b(purity|innocence|beauty\b|harmony|balance, harmony|cruelty|harshness|tolerance|forbearance|generosity|dignity|honou?r\b|virtue|vice\b|morality|ethics|justice\b|equality|freedom|liberty|truth\b|falsehood|essence|substance, essence|principle|concept|notion|abstraction|ideal\b|reality\b|existence|absence\b|presence\b|necessity|possibility|probability|certainty|ambiguity|contradiction|paradox|analogy|symbol|meaning\b|value\b|quality\b|quantity\b|origin\b|cause\b|effect\b|purpose\b|意|invalid|no effect|inefficiency|incompetence|efficiency|effectiveness|validity|superiority|inferiority|priority|majority\b|minority\b|extreme|moderation|excess\b|shortage\b)\b"),
("seishitsu","valoracion", r"\b(shameful|despicable|mean\b|remarkable|considerable|heartening|reassuring|graceful|elegant|vain\b|futile|vacant|heartbroken|romantic|feudalistic|magnificent|marvel|superb|awkward|absurd|ridiculous|obvious|apparent|vague|precise|strict|lenient|harsh|gentle\b|noble|humble\b|vulgar|refined|delicate|fragile|robust|steady|unstable)\b"),
("shizen","materia", r"\b(solution\b|alkali|acid\b|boiling|seething|evaporat|crystal|molecule|atom\b|cell\b|tissue\b|organism|specimen|compound|mixture|solvent|density|pressure\b|friction|combustion|radiation|magnetism|electron|proton|isotope)\b"),
("shizen","cielo", r"\b(constellation|galaxy|comet|meteor|orbit|eclipse|astronom)\b"),
("gijutsu","maquinas", r"\b(filter|timer|sensor|switchboard|generator|turbine|valve|pump\b|circuit\b|antenna|monitor\b|printer|misprint|ropeway|aerial tram|escalator|conveyor|crane\b)\b"),
("basho","transporte", r"\b(main line|trunk line|branch line|terminal|junction|monorail|tramway|runway|dock\b|pier\b)\b"),
("kokoro","relaciones", r"\b(errand|appointment, meeting|rendezvous|temptation|allurement|lure\b|seduction|persuasion|betrayal|loyalty|hospitality|courtesy, etiquette)\b"),
("jikan","cantidad", r"\b(depopulation|overpopulation|surplus, excess|deficit|percentage, ratio|average, mean|maximum|minimum|total, sum|density, concentration)\b"),
]
