# -*- coding: utf-8 -*-
"""Taxonomía temática del vocabulario N2: secciones -> subgrupos."""

# (id, etiqueta japonesa, etiqueta española)
SECCIONES = [
    ("hito",      "人と体",       "Personas y cuerpo"),
    ("kurashi",   "暮らし",       "Vida diaria"),
    ("jikan",     "時間と数",     "Tiempo y cantidad"),
    ("basho",     "場所と移動",   "Lugar y movimiento"),
    ("shizen",    "自然と天気",   "Naturaleza"),
    ("gakkou",    "学校と学び",   "Escuela y estudio"),
    ("shigoto",   "仕事と社会",   "Trabajo y sociedad"),
    ("kokoro",    "気持ちと人間関係", "Sentimientos y relaciones"),
    ("dousa",     "動きと行為",   "Acciones"),
    ("kotoba",    "考えと伝える", "Pensar y comunicar"),
    ("seishitsu", "性質と程度",   "Cualidades y grado"),
    ("gijutsu",   "技術・道具・文化", "Técnica, herramientas y cultura"),
    ("tsunagu",   "つなぐ言葉",   "Conectores y afijos"),
    ("sonota",    "その他",       "Otros"),
]

# seccion -> [(id_sub, ja, es)]
SUBGRUPOS = {
 "hito": [
   ("familia",     "家族",         "Familia"),
   ("cuerpo",      "体",           "El cuerpo"),
   ("salud",       "健康と病気",   "Salud y enfermedad"),
   ("apariencia",  "見た目",       "Apariencia"),
   ("caracter",    "性格",         "Carácter"),
   ("vida",        "人生と年齢",   "Vida y edad"),
   ("gente",       "人の呼び方",   "Personas y tratamiento"),
 ],
 "kurashi": [
   ("casa",        "家と住まい",   "Casa y vivienda"),
   ("muebles",     "家具と日用品", "Muebles y enseres"),
   ("comida",      "食べ物と飲み物","Comida y bebida"),
   ("cocina",      "料理と味",     "Cocina y sabor"),
   ("ropa",        "服とみだしなみ","Ropa y arreglo personal"),
   ("compras",     "買い物",       "Compras"),
   ("dinero",      "お金",         "Dinero"),
   ("rutina",      "毎日のこと",   "Rutina diaria"),
   ("limpieza",    "掃除と洗濯",   "Limpieza y lavado"),
 ],
 "jikan": [
   ("momento",     "時とタイミング","Momento y ocasión"),
   ("calendario",  "日・月・年",   "Calendario"),
   ("duracion",    "長さと速さ",   "Duración y velocidad"),
   ("frecuencia",  "回数と頻度",   "Frecuencia"),
   ("cantidad",    "量と数",       "Cantidad y número"),
   ("contadores",  "数え方",       "Contadores"),
   ("orden",       "順序",         "Orden y secuencia"),
 ],
 "basho": [
   ("ubicacion",   "位置と方向",   "Posición y dirección"),
   ("ciudad",      "町と建物",     "Ciudad y edificios"),
   ("transporte",  "乗り物",       "Transporte"),
   ("viaje",       "旅行",         "Viajes"),
   ("mundo",       "国と世界",     "Países y mundo"),
   ("ir_venir",    "行き来",       "Ir y venir"),
 ],
 "shizen": [
   ("clima",       "天気",         "Clima"),
   ("cielo",       "空と宇宙",     "Cielo y universo"),
   ("tierra",      "土地と地形",   "Tierra y relieve"),
   ("agua",        "水と海",       "Agua y mar"),
   ("plantas",     "植物",         "Plantas"),
   ("animales",    "動物",         "Animales"),
   ("materia",     "物質と材料",   "Materia y materiales"),
   ("desastre",    "災害と危険",   "Desastres y peligro"),
 ],
 "gakkou": [
   ("escuela",     "学校",         "La escuela"),
   ("estudio",     "勉強",         "Estudiar"),
   ("examen",      "試験",         "Exámenes"),
   ("lengua",      "ことばと文字", "Lengua y escritura"),
   ("libros",      "本と読み書き", "Libros y escritura"),
   ("materias",    "科目と学問",   "Materias y disciplinas"),
 ],
 "shigoto": [
   ("trabajo",     "仕事",         "El trabajo"),
   ("empresa",     "会社",         "La empresa"),
   ("oficios",     "職業",         "Oficios"),
   ("economia",    "経済と産業",   "Economía e industria"),
   ("politica",    "政治",         "Política"),
   ("ley",         "法律と犯罪",   "Ley y delito"),
   ("guerra",      "戦争と軍",     "Guerra y ejército"),
   ("sociedad",    "社会と制度",   "Sociedad e instituciones"),
   ("campo",       "農業と漁業",   "Campo y pesca"),
 ],
 "kokoro": [
   ("alegria",     "うれしい気持ち","Emociones agradables"),
   ("tristeza",    "つらい気持ち", "Emociones difíciles"),
   ("deseo",       "望みと意志",   "Deseo y voluntad"),
   ("relaciones",  "人づきあい",   "Trato con la gente"),
   ("saludos",     "あいさつ",     "Saludos y fórmulas"),
   ("actitud",     "態度とふるまい","Actitud y conducta"),
 ],
 "dousa": [
   ("mano",        "手を使う",     "Usar las manos"),
   ("movimiento",  "体の動き",     "Movimientos del cuerpo"),
   ("dar_recibir", "やりもらい",   "Dar y recibir"),
   ("hacer",       "作ると直す",   "Hacer y arreglar"),
   ("romper",      "こわすと なくす","Romper y perder"),
   ("colocar",     "置くと入れる", "Colocar y meter"),
   ("percepcion",  "見る・聞く・感じる","Ver, oír, sentir"),
   ("conflicto",   "戦うと争う",   "Luchar y competir"),
   ("abstractas",  "抽象的な行為", "Acciones abstractas"),
 ],
 "kotoba": [
   ("pensar",      "考える",       "Pensar"),
   ("saber",       "知るとわかる", "Saber y entender"),
   ("decir",       "言う",         "Decir"),
   ("preguntar",   "聞くと答える", "Preguntar y responder"),
   ("opinion",     "意見と議論",   "Opinión y debate"),
   ("verdad",      "本当とうそ",   "Verdad y mentira"),
   ("decidir",     "決めると計画", "Decidir y planear"),
 ],
 "seishitsu": [
   ("forma",       "大きさと形",   "Tamaño y forma"),
   ("color",       "色",           "Colores"),
   ("valoracion",  "よいとわるい", "Bueno y malo"),
   ("dificultad",  "難しいとやさしい","Fácil y difícil"),
   ("grado",       "程度",         "Grado e intensidad"),
   ("comparacion", "比べる",       "Comparar"),
   ("estado",      "ようすと状態", "Estados y apariencia"),
   ("conceptos",   "抽象概念",     "Conceptos abstractos"),
 ],
 "gijutsu": [
   ("maquinas",    "機械",         "Máquinas"),
   ("energia",     "電気とエネルギー","Electricidad y energía"),
   ("medios",      "通信とメディア","Comunicación y medios"),
   ("herramientas","道具",         "Herramientas"),
   ("arte",        "芸術",         "Arte"),
   ("musica",      "音楽",         "Música"),
   ("deporte",     "スポーツ",     "Deporte"),
   ("ocio",        "遊びと趣味",   "Ocio y aficiones"),
   ("creencias",   "宗教と行事",   "Creencias y celebraciones"),
 ],
 "tsunagu": [
   ("conjunciones","接続詞",       "Conjunciones"),
   ("kosoado",     "こそあど",     "Demostrativos"),
   ("pronombres",  "代名詞と疑問詞","Pronombres e interrogativos"),
   ("afijos",      "接頭語と接尾語","Prefijos y sufijos"),
   ("formulas",    "決まり文句",   "Expresiones fijas"),
   ("adverbios",   "副詞",         "Adverbios"),
 ],
 "sonota": [
   ("sustantivos", "その他の名詞", "Otros sustantivos"),
   ("verbos",      "その他の動詞", "Otros verbos"),
   ("adjetivos",   "その他の形容詞","Otros adjetivos"),
   ("varios",      "そのほか",     "Varios"),
 ],
}
