# -*- coding: utf-8 -*-
"""Taxonomía temática del vocabulario: secciones -> subgrupos.

Cada etiqueta va en los tres idiomas del sitio. El inglés no es decorativo:
sin él, quien tiene la interfaz en inglés navegaba el curso entero —secciones,
unidades, cabeceras— leyendo español.
"""

# (id, etiqueta japonesa, etiqueta española, etiqueta inglesa)
SECCIONES = [
    ("hito",      "人と体",       "Personas y cuerpo", "People and body"),
    ("kurashi",   "暮らし",       "Vida diaria", "Daily life"),
    ("jikan",     "時間と数",     "Tiempo y cantidad", "Time and quantity"),
    ("basho",     "場所と移動",   "Lugar y movimiento", "Place and movement"),
    ("shizen",    "自然と天気",   "Naturaleza", "Nature"),
    ("gakkou",    "学校と学び",   "Escuela y estudio", "School and study"),
    ("shigoto",   "仕事と社会",   "Trabajo y sociedad", "Work and society"),
    ("kokoro",    "気持ちと人間関係", "Sentimientos y relaciones", "Feelings and relationships"),
    ("dousa",     "動きと行為",   "Acciones", "Actions"),
    ("kotoba",    "考えと伝える", "Pensar y comunicar", "Thinking and communicating"),
    ("seishitsu", "性質と程度",   "Cualidades y grado", "Qualities and degree"),
    ("gijutsu",   "技術・道具・文化", "Técnica, herramientas y cultura", "Technology, tools and culture"),
    ("tsunagu",   "つなぐ言葉",   "Conectores y afijos", "Connecting words"),
    ("sonota",    "その他",       "Otros", "Other"),
]

# seccion -> [(id_sub, ja, es, en)]
SUBGRUPOS = {
 "hito": [
   ("familia",     "家族",         "Familia", "Family"),
   ("cuerpo",      "体",           "El cuerpo", "The body"),
   ("salud",       "健康と病気",   "Salud y enfermedad", "Health and illness"),
   ("apariencia",  "見た目",       "Apariencia", "Appearance"),
   ("caracter",    "性格",         "Carácter", "Character"),
   ("vida",        "人生と年齢",   "Vida y edad", "Life and age"),
   ("gente",       "人の呼び方",   "Personas y tratamiento", "People and forms of address"),
 ],
 "kurashi": [
   ("casa",        "家と住まい",   "Casa y vivienda", "House and home"),
   ("muebles",     "家具と日用品", "Muebles y enseres", "Furniture and household goods"),
   ("comida",      "食べ物と飲み物","Comida y bebida", "Food and drink"),
   ("cocina",      "料理と味",     "Cocina y sabor", "Cooking and flavour"),
   ("ropa",        "服とみだしなみ","Ropa y arreglo personal", "Clothes and grooming"),
   ("compras",     "買い物",       "Compras", "Shopping"),
   ("dinero",      "お金",         "Dinero", "Money"),
   ("rutina",      "毎日のこと",   "Rutina diaria", "Daily routine"),
   ("limpieza",    "掃除と洗濯",   "Limpieza y lavado", "Cleaning and laundry"),
 ],
 "jikan": [
   ("momento",     "時とタイミング","Momento y ocasión", "Time and occasion"),
   ("calendario",  "日・月・年",   "Calendario", "Calendar"),
   ("duracion",    "長さと速さ",   "Duración y velocidad", "Duration and speed"),
   ("frecuencia",  "回数と頻度",   "Frecuencia", "Frequency"),
   ("cantidad",    "量と数",       "Cantidad y número", "Quantity and number"),
   ("contadores",  "数え方",       "Contadores", "Counters"),
   ("orden",       "順序",         "Orden y secuencia", "Order and sequence"),
 ],
 "basho": [
   ("ubicacion",   "位置と方向",   "Posición y dirección", "Position and direction"),
   ("ciudad",      "町と建物",     "Ciudad y edificios", "Town and buildings"),
   ("transporte",  "乗り物",       "Transporte", "Transport"),
   ("viaje",       "旅行",         "Viajes", "Travel"),
   ("mundo",       "国と世界",     "Países y mundo", "Countries and the world"),
   ("ir_venir",    "行き来",       "Ir y venir", "Coming and going"),
 ],
 "shizen": [
   ("clima",       "天気",         "Clima", "Weather"),
   ("cielo",       "空と宇宙",     "Cielo y universo", "Sky and space"),
   ("tierra",      "土地と地形",   "Tierra y relieve", "Land and terrain"),
   ("agua",        "水と海",       "Agua y mar", "Water and sea"),
   ("plantas",     "植物",         "Plantas", "Plants"),
   ("animales",    "動物",         "Animales", "Animals"),
   ("materia",     "物質と材料",   "Materia y materiales", "Matter and materials"),
   ("desastre",    "災害と危険",   "Desastres y peligro", "Disasters and danger"),
 ],
 "gakkou": [
   ("escuela",     "学校",         "La escuela", "School"),
   ("estudio",     "勉強",         "Estudiar", "Studying"),
   ("examen",      "試験",         "Exámenes", "Exams"),
   ("lengua",      "ことばと文字", "Lengua y escritura", "Language and writing"),
   ("libros",      "本と読み書き", "Libros y escritura", "Books and writing"),
   ("materias",    "科目と学問",   "Materias y disciplinas", "Subjects and disciplines"),
 ],
 "shigoto": [
   ("trabajo",     "仕事",         "El trabajo", "Work"),
   ("empresa",     "会社",         "La empresa", "The company"),
   ("oficios",     "職業",         "Oficios", "Occupations"),
   ("economia",    "経済と産業",   "Economía e industria", "Economy and industry"),
   ("politica",    "政治",         "Política", "Politics"),
   ("ley",         "法律と犯罪",   "Ley y delito", "Law and crime"),
   ("guerra",      "戦争と軍",     "Guerra y ejército", "War and the military"),
   ("sociedad",    "社会と制度",   "Sociedad e instituciones", "Society and institutions"),
   ("campo",       "農業と漁業",   "Campo y pesca", "Farming and fishing"),
 ],
 "kokoro": [
   ("alegria",     "うれしい気持ち","Emociones agradables", "Pleasant feelings"),
   ("tristeza",    "つらい気持ち", "Emociones difíciles", "Difficult feelings"),
   ("deseo",       "望みと意志",   "Deseo y voluntad", "Wishes and will"),
   ("relaciones",  "人づきあい",   "Trato con la gente", "Getting on with people"),
   ("saludos",     "あいさつ",     "Saludos y fórmulas", "Greetings and set phrases"),
   ("actitud",     "態度とふるまい","Actitud y conducta", "Attitude and conduct"),
 ],
 "dousa": [
   ("mano",        "手を使う",     "Usar las manos", "Using your hands"),
   ("movimiento",  "体の動き",     "Movimientos del cuerpo", "Body movements"),
   ("dar_recibir", "やりもらい",   "Dar y recibir", "Giving and receiving"),
   ("hacer",       "作ると直す",   "Hacer y arreglar", "Making and mending"),
   ("romper",      "こわすと なくす","Romper y perder", "Breaking and losing"),
   ("colocar",     "置くと入れる", "Colocar y meter", "Placing and putting in"),
   ("percepcion",  "見る・聞く・感じる","Ver, oír, sentir", "Seeing, hearing, feeling"),
   ("conflicto",   "戦うと争う",   "Luchar y competir", "Fighting and competing"),
   ("abstractas",  "抽象的な行為", "Acciones abstractas", "Abstract actions"),
 ],
 "kotoba": [
   ("pensar",      "考える",       "Pensar", "Thinking"),
   ("saber",       "知るとわかる", "Saber y entender", "Knowing and understanding"),
   ("decir",       "言う",         "Decir", "Saying"),
   ("preguntar",   "聞くと答える", "Preguntar y responder", "Asking and answering"),
   ("opinion",     "意見と議論",   "Opinión y debate", "Opinion and debate"),
   ("verdad",      "本当とうそ",   "Verdad y mentira", "Truth and lies"),
   ("decidir",     "決めると計画", "Decidir y planear", "Deciding and planning"),
 ],
 "seishitsu": [
   ("forma",       "大きさと形",   "Tamaño y forma", "Size and shape"),
   ("color",       "色",           "Colores", "Colours"),
   ("valoracion",  "よいとわるい", "Bueno y malo", "Good and bad"),
   ("dificultad",  "難しいとやさしい","Fácil y difícil", "Easy and difficult"),
   ("grado",       "程度",         "Grado e intensidad", "Degree and intensity"),
   ("comparacion", "比べる",       "Comparar", "Comparing"),
   ("estado",      "ようすと状態", "Estados y apariencia", "States and appearance"),
   ("conceptos",   "抽象概念",     "Conceptos abstractos", "Abstract concepts"),
 ],
 "gijutsu": [
   ("maquinas",    "機械",         "Máquinas", "Machines"),
   ("energia",     "電気とエネルギー","Electricidad y energía", "Electricity and energy"),
   ("medios",      "通信とメディア","Comunicación y medios", "Communication and media"),
   ("herramientas","道具",         "Herramientas", "Tools"),
   ("arte",        "芸術",         "Arte", "Art"),
   ("musica",      "音楽",         "Música", "Music"),
   ("deporte",     "スポーツ",     "Deporte", "Sport"),
   ("ocio",        "遊びと趣味",   "Ocio y aficiones", "Leisure and hobbies"),
   ("creencias",   "宗教と行事",   "Creencias y celebraciones", "Beliefs and celebrations"),
 ],
 "tsunagu": [
   ("conjunciones","接続詞",       "Conjunciones", "Conjunctions"),
   ("kosoado",     "こそあど",     "Demostrativos", "Demonstratives"),
   ("pronombres",  "代名詞と疑問詞","Pronombres e interrogativos", "Pronouns and question words"),
   ("afijos",      "接頭語と接尾語","Prefijos y sufijos", "Prefixes and suffixes"),
   ("formulas",    "決まり文句",   "Expresiones fijas", "Set expressions"),
   ("adverbios",   "副詞",         "Adverbios", "Adverbs"),
 ],
 "sonota": [
   ("sustantivos", "その他の名詞", "Otros sustantivos", "Other nouns"),
   ("verbos",      "その他の動詞", "Otros verbos", "Other verbs"),
   ("adjetivos",   "その他の形容詞","Otros adjetivos", "Other adjectives"),
   ("varios",      "そのほか",     "Varios", "Miscellaneous"),
 ],
}
